### ISSUE TITLE
Local Storage?

### ISSUE THREAD

**Issue by BlackIQ** [mehrabmp/react-wordle#1]
سلام.

دیدم که سلوشن توی لوکال استوریج ذخیره شده.
یه توییت داشتم گفتم به دستت ایشالله میرسه ولی حواسم به ایشو ها نبود.

حالا اگه وقت داشتی توییت رو ببین بیشتر توضیح دادم.

https://twitter.com/GNU_Amir/status/1523039742719315970

امیرحسین.

**Comment by mehrabmp** [comment]
Fixed.
